#!/bin/bash
# Codex adversarial review runner (Slash plugin 経由)
set +e
cd /private/tmp/cardene777

# codex-plugin の場所を解決
PLUGIN_ROOT="${CLAUDE_PLUGIN_ROOT:-}"
if [ -z "$PLUGIN_ROOT" ]; then
  for cand in \
    "$HOME/.claude/plugins/marketplaces/openai-codex/plugins/codex" \
    "$HOME/.claude/plugins/codex" \
    "$HOME/.codex/plugin"; do
    if [ -d "$cand" ]; then
      PLUGIN_ROOT="$cand"
      break
    fi
  done
fi

# fallback: codex CLI 直接
if [ -z "$PLUGIN_ROOT" ] || [ ! -f "$PLUGIN_ROOT/scripts/codex-companion.mjs" ]; then
  echo "[Codex] plugin not found, fallback to direct codex CLI" >&2
  # plugin root が見つからない場合は codex CLI 直接で adversarial レビュー
  cat > .context/local-review/codex-prompt.txt <<EOF
You are an adversarial code reviewer. Review the diff between main and HEAD on this repository.

CONTEXT: This PR redesigns a GitHub profile README + adds a GitHub Pages full-profile site (docs/index.html + docs/style.css) + CI workflows (waka-readme, profile-3d, snake) + an SVG logo + 3D contrib settings.

EXCLUDE FROM REVIEW: profile-summary-card-output/**/*.svg (auto-generated by GH Action, only timestamp updates)

FOCUS:
1. README.md: GitHub markdown sanitization compliance (no <style>/<script>/on*/background-color), external image URL availability/rate-limit, WakaTime <!--START_SECTION:waka--> marker pairing
2. docs/index.html: inline <style> + external style.css collision, image src reachability, leftover "[sample] cardene777 の 3D 草に置換予定" text, Jekyll .nojekyll requirement for /docs publishing
3. docs/style.css: scope leakage, OS font fallback for JetBrains Mono
4. .github/workflows/*.yml: floating ref pinning (anmol098/waka-readme-stats@master), permissions block, cron schedule conflicts, secret handling
5. assets/logo-cardene.svg: <style><![CDATA[]]></style> rendering on GitHub raw SVG, glow filter sanitization
6. profile-3d-contrib/settings.json: schema validity, fileName matches README img path

REJECT (treat as bugs even if "minor"):
- Floating action ref (master/main) instead of @vN or commit SHA
- External image URL with Mixed Content / 404 risk
- Leftover placeholder text ([sample], TODO, FIXME) shipped to main
- Workflow secrets printed to log
- Hardcoded user-specific paths

SEVERITY:
- CRITICAL: secret leak, supply chain, broken page rendering
- MAJOR: floating ref, leftover placeholder, missing permissions
- MINOR: style nits, deprecated HTML attributes, comment typos

OUTPUT FORMAT (max 30 findings):
## CRITICAL
- [path:line] summary — suggestion

## MAJOR
- [path:line] summary — suggestion

## MINOR
- [path:line] summary — suggestion
EOF

  codex exec --full-auto --skip-git-repo-check -m gpt-5.4 -C /private/tmp/cardene777 \
    "$(cat .context/local-review/codex-prompt.txt)" \
    > .context/local-review/codex-result.txt \
    2> .context/local-review/codex-stderr.txt
  echo $? > .context/local-review/codex-exit-code
else
  node "$PLUGIN_ROOT/scripts/codex-companion.mjs" adversarial-review \
    --base main \
    "Focus: GitHub markdown sanitization, GitHub Pages publishing, action ref pinning, SVG/CSS sanitization. Reject: floating refs, leftover placeholders, missing permissions. Context: profile README + Pages + CI workflows redesign for cardene777/cardene777." \
    > .context/local-review/codex-result.txt \
    2> .context/local-review/codex-stderr.txt
  echo $? > .context/local-review/codex-exit-code
fi

echo "[Codex] exit=$(cat .context/local-review/codex-exit-code) outsize=$(wc -c < .context/local-review/codex-result.txt) bytes"
