name: snek go brr

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: snek vector born
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            buidl/snek-light.svg?palette=github-light&color_snake=#22c55e&color_dots=#16302a,#22c55e,#4ade80,#86efac,#d1fae5
            buidl/snek-dark.svg?color_snake=#4ade80&color_dots=#000000,#16302a,#22c55e,#4ade80,#86efac

      - name: snek slither to page
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: snek
          build_dir: buidl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
